title: カネコってるブログ
description: >
  技術備忘録／日記／雑多な感じのブログです。<br/>
  本ブログの情報は所属する組織の見解／知見ではなく個人の見解／知見であり、正確性や合法性や安全性を保証するものではありません。

baseurl: ""
logo_path: "/assets/images/top_dir/logo.png"
url: "https://blog.k636174.net/"

include: ['_pages']

author:
  name: k636174
  email: shinji@k636174.net
  github: k636174
  twitter: k636174
  facebook: k636174

paginate: 23
paginate_path: "page:num"

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
#  - jekyll-sitemap